name: archethic_lib_dart
description: ArchEthic dart library for Flutter for Node and Browser. This library aims to provide a easy way to create ArchEthic transaction and to send them over the network
homepage: https://github.com/archethic-foundation/libdart

version: 0.2.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  # Implementations of SHA, MD5, and HMAC cryptographic functions
  crypto: ^3.0.1

  # A library for doing cryptographic signing/verifying and encrypting/decrypting.
  crypto_keys: ^0.3.0

  # Package ecdsa implements the Elliptic Curve Digital Signature Algorithm, as defined in FIPS 186-3
  ecdsa: ^0.0.4

  # basic elliptic curves
  elliptic: ^0.3.5

  # A composable, multi-platform, Future-based API for HTTP requests
  http: ^0.13.3

  # The Dart implementation of the PyNaCl APIs with the TweetNaCl cryptographic library
  pinenacl: ^0.3.3

  # A Dart library implementing cryptographic algorithms and primitives, modeled on the BouncyCastle library
  pointycastle: ^3.1.3

  # Pure secp256k1 signature algorithm implement for dart language which uses pure dart and basic types to represent all matters
  secp256k1: ^0.3.0

  # Dart port of Curve25519
  x25519: ^0.0.2

dev_dependencies:
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  test: ^1.17.10