# SPDX-License-Identifier: AGPL-3.0-or-later
name: archethic_lib_dart
description: Archethic dart library for Flutter for Node and Browser. This library aims to provide a easy way to create Archethic transaction and to send them over the network
homepage: https://github.com/archethic-foundation/libdart

version: 1.0.27

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:

  # A Dart library to encode and decode various archive and compression formats.
  # archive: ^3.2.1

  # Implementations of SHA, MD5, and HMAC cryptographic functions
  crypto: ^3.0.2

  # A library for doing cryptographic signing/verifying and encrypting/decrypting.
  crypto_keys: ^0.3.0

  # Package ecdsa implements the Elliptic Curve Digital Signature Algorithm, as defined in FIPS 186-3
  ecdsa: ^0.0.4

  # basic elliptic curves
  elliptic: ^0.3.8

  # Annotations for the freezed code-generator. This package does nothing without freezed too
  freezed_annotation: ^2.2.0

  # GraphQL client
  gql: ^0.14.0
  graphql: ^5.1.1

  # Easy hexadecimal convertion using dart:convert API.
  hex: ^0.2.0

  # A composable, multi-platform, Future-based API for HTTP requests
  http: ^0.13.5

  # Annotations for the JsonSerializable code-generator.
  json_annotation: ^4.7.0

  # JWK (JSON Web Key) encoding and decoding
  jwk: ^0.1.1
  
  # The Dart implementation of the PyNaCl APIs with the TweetNaCl cryptographic library
  pinenacl: ^0.5.1

  # A Dart library implementing cryptographic algorithms and primitives, modeled on the BouncyCastle library
  pointycastle: ^3.6.2

  # Pure secp256k1 signature algorithm implement for dart language which uses pure dart and basic types to represent all matters
  secp256k1: ^0.3.0

  # Dart port of Curve25519
  x25519: ^0.1.1

dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.2.1
  
  flutter_lints: ^2.0.1

  # Code generation for immutable classes that has a simple syntax/API without compromising on the features
  freezed: ^2.2.1

  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  json_serializable: ^6.5.4
  test: ^1.21.4