# SPDX-License-Identifier: AGPL-3.0-or-later
name: archethic_lib_dart
description: Archethic dart library for Flutter for Node and Browser. This library aims to provide a easy way to create Archethic transaction and to send them over the network
homepage: https://github.com/archethic-foundation/libdart

version: 4.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  # Collections and utilities functions and classes related to collections.
  collection: ^1.18.0

  # Implementations of SHA, MD5, and HMAC cryptographic functions
  crypto: ^3.0.3

  # The decimal package allows you to deal with decimal numbers without losing precision
  decimal: ^3.0.2

  # Package ecdsa implements the Elliptic Curve Digital Signature Algorithm, as defined in FIPS 186-3
  ecdsa: ^0.1.0

  # basic elliptic curves
  elliptic: ^0.3.10

  # Annotations for the freezed code-generator. This package does nothing without freezed too
  freezed_annotation: ^2.4.1

  # GraphQL tools for parsing, transforming and printing GraphQL documents.
  gql: ^1.0.0+1

  # A stand-alone GraphQL client for Dart, bringing all the features from a modern GraphQL client to one easy to use package.
  graphql: ^5.1.3

  # A composable, multi-platform, Future-based API for HTTP requests
  http: ^1.2.1

  # JWK (JSON Web Key) encoding and decoding
  jwk: ^0.2.3

  # Provides APIs for debugging and error logging, similar to loggers in other languages, such as the Closure JS Logger and java.util.logging.Logger.
  logging: ^1.2.0

  # PhoenixSocket provides a feature-complete implementation of Phoenix Sockets, using a single API based on StreamChannels compatible with any deployment of Flutter
  phoenix_socket: ^0.7.4

  # The Dart implementation of the PyNaCl APIs with the TweetNaCl cryptographic library
  pinenacl: ^0.6.0

  # A Dart library implementing cryptographic algorithms and primitives, modeled on the BouncyCastle library
  pointycastle: ^3.9.1

  # Quiver is a set of utility libraries for Dart that makes using many Dart libraries easier and more convenient, or adds additional functionality.
  quiver: ^3.2.1

  # Dart port of Curve25519
  x25519: ^0.1.1

dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.11

  # A tool to help you find missing, under-promoted, over-promoted, and unused dependencies.
  dependency_validator: ^4.1.0

  # Code generation for immutable classes that has a simple syntax/API without compromising on the features
  freezed: ^2.4.7

  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.9.0

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.8.0

  # A full featured library for writing and running Dart tests across platforms.
  test: ^1.25.8
