# SPDX-License-Identifier: AGPL-3.0-or-later
name: archethic_lib_dart
description: Archethic dart library for Flutter for Node and Browser. This library aims to provide a easy way to create Archethic transaction and to send them over the network
homepage: https://github.com/archethic-foundation/libdart

version: 1.0.7

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  # A Dart library to encode and decode various archive and compression formats.
  # archive: ^3.2.1

  # Utilities for converting between data representations. Provides a number of Sink, Codec, Decoder, and Encoder types
  convert: ^3.0.1

  # Implementations of SHA, MD5, and HMAC cryptographic functions
  crypto: ^3.0.2

  # A library for doing cryptographic signing/verifying and encrypting/decrypting.
  crypto_keys: ^0.3.0

  # Package ecdsa implements the Elliptic Curve Digital Signature Algorithm, as defined in FIPS 186-3
  ecdsa: ^0.0.4

  # basic elliptic curves
  elliptic: ^0.3.6

  # A composable, multi-platform, Future-based API for HTTP requests
  http: ^0.13.4

  # JWK (JSON Web Key) encoding and decoding
  jwk: ^0.1.1

  # The Dart implementation of the PyNaCl APIs with the TweetNaCl cryptographic library
  pinenacl: ^0.3.4

  # A Dart library implementing cryptographic algorithms and primitives, modeled on the BouncyCastle library
  pointycastle: ^3.6.0

  # Pure secp256k1 signature algorithm implement for dart language which uses pure dart and basic types to represent all matters
  secp256k1: ^0.3.0

  # Dart port of Curve25519
  x25519: ^0.1.1

dev_dependencies:
  flutter_lints: ^1.0.4
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  test: ^1.21.1